spring:
  application:
    name: gwangju-talent-festival-server

  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  access-token-key: ${ACCESS_TOKEN_KEY}
  access-token-expires: 1800000
